version: '3'
services:
  pyspark-notebook:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /utility/postgresql-42.7.3.jar:/usr/local/spark/jars/postgresql_driver.jar
      - D:/test_release/Executive_Search/Executive_Search:/home/jovyan/work
    ports:
      - "8888:8888"
      - "4040:4040"      
    # networks:
    #   - thrive_nxgen
  
# networks:
#   thrive_nxgen:
#     external: true
#     name: phoenix-network
